import type { SkillCategory, Skill } from "@/types";

/**
 * Technical Competencies & Skill Matrix
 * Categorized technical skills supported by project evidence.
 */
export const skillCategories: ReadonlyArray<SkillCategory> = [
  {
    id: "cat-backend",
    name: "Backend",
    description: "High-performance REST APIs, server microservices, and asynchronous event loops.",
    displayOrder: 1,
    skills: [
      {
        id: "sk-fastapi",
        name: "FastAPI",
        slug: "fastapi",
        categoryId: "cat-backend",
        proficiency: "expert",
        yearsOfExperience: 2,
        iconName: "Zap",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-nodejs",
        name: "Node.js",
        slug: "nodejs",
        categoryId: "cat-backend",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "Server",
        verifiedProjectIds: ["smart-agriculture-portal"],
        isFeatured: true,
      },
      {
        id: "sk-express",
        name: "Express.js",
        slug: "express",
        categoryId: "cat-backend",
        proficiency: "expert",
        yearsOfExperience: 2,
        iconName: "Cpu",
        verifiedProjectIds: ["smart-agriculture-portal", "gaslytics"],
        isFeatured: true,
      },
    ],
  },
  {
    id: "cat-frontend",
    name: "Frontend",
    description: "Building responsive web interfaces, modern component design systems, and SPA/SSG applications.",
    displayOrder: 2,
    skills: [
      {
        id: "sk-react",
        name: "React",
        slug: "react",
        categoryId: "cat-frontend",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "Atom",
        verifiedProjectIds: ["cognitoshield-ai", "smart-agriculture-portal"],
        isFeatured: true,
      },
      {
        id: "sk-next",
        name: "Next.js",
        slug: "nextjs",
        categoryId: "cat-frontend",
        proficiency: "expert",
        yearsOfExperience: 2,
        iconName: "Globe",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
    ],
  },
  {
    id: "cat-databases",
    name: "Databases",
    description: "Relational database engines, indexing strategies, time-series telemetry storage, and embedded persistence.",
    displayOrder: 3,
    skills: [
      {
        id: "sk-sqlite",
        name: "SQLite",
        slug: "sqlite",
        categoryId: "cat-databases",
        proficiency: "expert",
        yearsOfExperience: 2,
        iconName: "HardDrive",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-mysql",
        name: "MySQL",
        slug: "mysql",
        categoryId: "cat-databases",
        proficiency: "proficient",
        yearsOfExperience: 2,
        iconName: "Database",
        verifiedProjectIds: ["smart-agriculture-portal", "gaslytics"],
        isFeatured: true,
      },
    ],
  },
  {
    id: "cat-ml",
    name: "Machine Learning",
    description: "Predictive analytics models, data transformation pipelines, and gradient boosting algorithms.",
    displayOrder: 4,
    skills: [
      {
        id: "sk-scikit",
        name: "Scikit-Learn",
        slug: "scikit-learn",
        categoryId: "cat-ml",
        proficiency: "proficient",
        yearsOfExperience: 2,
        iconName: "BrainCircuit",
        verifiedProjectIds: ["gaslytics"],
        isFeatured: true,
      },
      {
        id: "sk-xgboost",
        name: "XGBoost",
        slug: "xgboost",
        categoryId: "cat-ml",
        proficiency: "proficient",
        yearsOfExperience: 2,
        iconName: "TrendingUp",
        verifiedProjectIds: ["gaslytics"],
        isFeatured: true,
      },
    ],
  },
  {
    id: "cat-devops",
    name: "Developer Tools",
    description: "Containerization runtimes, version control, and production build pipelines.",
    displayOrder: 5,
    skills: [
      {
        id: "sk-git",
        name: "Git",
        slug: "git",
        categoryId: "cat-devops",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "GitBranch",
        verifiedProjectIds: ["cognitoshield-ai", "smart-agriculture-portal", "gaslytics"],
        isFeatured: true,
      },
      {
        id: "sk-docker",
        name: "Docker",
        slug: "docker",
        categoryId: "cat-devops",
        proficiency: "proficient",
        yearsOfExperience: 2,
        iconName: "Container",
        verifiedProjectIds: ["cognitoshield-ai", "smart-agriculture-portal", "gaslytics"],
        isFeatured: true,
      },
    ],
  },
  {
    id: "cat-languages",
    name: "Languages",
    description: "Core programming languages and foundational computer science paradigms.",
    displayOrder: 6,
    skills: [
      {
        id: "sk-python",
        name: "Python",
        slug: "python",
        categoryId: "cat-languages",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "FileCode",
        verifiedProjectIds: ["cognitoshield-ai", "smart-agriculture-portal", "gaslytics"],
        isFeatured: true,
      },
      {
        id: "sk-java",
        name: "Java",
        slug: "java",
        categoryId: "cat-languages",
        proficiency: "proficient",
        yearsOfExperience: 2,
        iconName: "Code2",
        verifiedProjectIds: [],
        isFeatured: true,
      },
      {
        id: "sk-sql",
        name: "SQL",
        slug: "sql",
        categoryId: "cat-languages",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "Database",
        verifiedProjectIds: ["smart-agriculture-portal", "gaslytics"],
        isFeatured: true,
      },
      {
        id: "sk-c",
        name: "C",
        slug: "c",
        categoryId: "cat-languages",
        proficiency: "competent",
        yearsOfExperience: 2,
        iconName: "Terminal",
        verifiedProjectIds: [],
        isFeatured: true,
      },
    ],
  },
];

/**
 * Flat list of all featured hero tech stack skills for direct mapping.
 */
export const heroTechStackSkills: ReadonlyArray<Skill> = skillCategories.flatMap(
  (cat) => cat.skills.filter((skill) => skill.isFeatured)
);
