import type { SkillCategory } from "@/types";

/**
 * Tech Radar & Skill Categories Matrix
 */
export const skillCategories: ReadonlyArray<SkillCategory> = [
  {
    id: "cat-frontend",
    name: "Frontend & UI Architecture",
    description: "Building accessible, sub-50ms responsive user interfaces and scalable design token systems.",
    displayOrder: 1,
    skills: [
      {
        id: "sk-ts",
        name: "TypeScript",
        slug: "typescript",
        categoryId: "cat-frontend",
        proficiency: "expert",
        yearsOfExperience: 4,
        iconName: "FileCode",
        verifiedProjectIds: ["portfolio-v2", "cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-next",
        name: "Next.js 14+ (App Router)",
        slug: "nextjs",
        categoryId: "cat-frontend",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "Globe",
        verifiedProjectIds: ["portfolio-v2", "cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-react",
        name: "React 18",
        slug: "react",
        categoryId: "cat-frontend",
        proficiency: "expert",
        yearsOfExperience: 4,
        iconName: "Atom",
        verifiedProjectIds: ["portfolio-v2", "cognitoshield-ai", "fintech-ui-system"],
        isFeatured: true,
      },
      {
        id: "sk-tailwind",
        name: "Tailwind CSS",
        slug: "tailwindcss",
        categoryId: "cat-frontend",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "Palette",
        verifiedProjectIds: ["portfolio-v2", "cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-flutter",
        name: "Flutter / Dart",
        slug: "flutter",
        categoryId: "cat-frontend",
        proficiency: "proficient",
        yearsOfExperience: 2,
        iconName: "Smartphone",
        verifiedProjectIds: ["fintech-ui-system"],
        isFeatured: false,
      },
    ],
  },
  {
    id: "cat-backend",
    name: "Backend & Distributed Systems",
    description: "Architecting high-throughput microservices, REST/gRPC APIs, and event-driven backends.",
    displayOrder: 2,
    skills: [
      {
        id: "sk-node",
        name: "Node.js / Express",
        slug: "nodejs",
        categoryId: "cat-backend",
        proficiency: "expert",
        yearsOfExperience: 4,
        iconName: "Server",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-py",
        name: "Python / FastAPI",
        slug: "fastapi",
        categoryId: "cat-backend",
        proficiency: "expert",
        yearsOfExperience: 3,
        iconName: "Terminal",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-rest",
        name: "REST & WebSockets",
        slug: "rest-websockets",
        categoryId: "cat-backend",
        proficiency: "expert",
        yearsOfExperience: 4,
        iconName: "Radio",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
    ],
  },
  {
    id: "cat-data",
    name: "Databases & Storage",
    description: "Designing relational relational schemas, Redis caching layers, and high-speed query indexing.",
    displayOrder: 3,
    skills: [
      {
        id: "sk-pg",
        name: "PostgreSQL",
        slug: "postgresql",
        categoryId: "cat-data",
        proficiency: "expert",
        yearsOfExperience: 4,
        iconName: "Database",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-redis",
        name: "Redis",
        slug: "redis",
        categoryId: "cat-data",
        proficiency: "proficient",
        yearsOfExperience: 3,
        iconName: "Zap",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
    ],
  },
  {
    id: "cat-devops",
    name: "Infrastructure & Testing",
    description: "Containerization, automated CI/CD pipelines, and WCAG accessibility testing.",
    displayOrder: 4,
    skills: [
      {
        id: "sk-docker",
        name: "Docker & Containerization",
        slug: "docker",
        categoryId: "cat-devops",
        proficiency: "proficient",
        yearsOfExperience: 3,
        iconName: "Container",
        verifiedProjectIds: ["cognitoshield-ai"],
        isFeatured: true,
      },
      {
        id: "sk-git",
        name: "Git & GitHub Actions",
        slug: "git-ci-cd",
        categoryId: "cat-devops",
        proficiency: "expert",
        yearsOfExperience: 4,
        iconName: "GitBranch",
        verifiedProjectIds: ["portfolio-v2", "cognitoshield-ai"],
        isFeatured: true,
      },
    ],
  },
];
